spring:
  profiles:
    active: dev
  application:
    name: BusinessProSuiteAPI
  devtools:
    restart:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  
  # Configuración base de datos MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/BusinessProSuite?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  # Configuración JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false

  # Deshabilitar Flyway temporalmente para tests
  flyway:
    enabled: false

  # Configuración de cache
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

# Configuración del servidor
server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 100
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Configuración de seguridad JWT
jwt:
  secret: ${JWT_SECRET:BusinessProSuiteSecretKey2024MustBe256BitsForHS256AlgorithmSoThisIsAVeryLongSecretKeyToEnsureProperSecurity}
  expiration: ${JWT_EXPIRATION:86400000} # 24 horas en milisegundos

# Configuración de logging
logging:
  level:
    com.businessprosuite: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración de actuator para monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized

# Configuración de la aplicación
app:
  version: "V0.2"
  description: "BusinessProSuite API - Sistema integral de gestión empresarial"

# Configuración de SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    show-extensions: true
    show-common-extensions: true
  group-configs:
    - group: "auth"
      display-name: "🔐 Autenticación"
      paths-to-match: "/auth/**"
    - group: "users"
      display-name: "👥 Gestión de Usuarios"
      paths-to-match: "/api/users/**"
    - group: "companies"
      display-name: "🏢 Gestión de Empresas"
      paths-to-match: "/api/companies/**"
    - group: "finance"
      display-name: "💰 Módulo Financiero"
      paths-to-match: "/api/finance/**"
    - group: "hr"
      display-name: "👨‍💼 Recursos Humanos"
      paths-to-match: "/api/hr/**"
    - group: "inventory"
      display-name: "📦 Inventario"
      paths-to-match: "/api/inventory/**"
    - group: "analytics"
      display-name: "📊 Analytics"
      paths-to-match: "/api/analytics/**"
    - group: "admin"
      display-name: "⚙️ Administración"
      paths-to-match: "/api/admin/**" 